export const WALK1 = 'walk1';
export const WALK2 = 'walk2';
export const JUMP = 'jump';
export const PRONE = 'prone';
export const PRONE_STAB = 'proneStab';
export const STAND1 = 'stand1';
export const STAND2 = 'stand2';
export const FLY = 'fly';
export const ROPE = 'rope';
export const LADDER = 'ladder';
export const SIT = 'sit';
export const ALERT = 'alert';
export const HEAL = 'heal';
export const SHOOT1 = 'shoot1'; //Bow
export const SHOOT2 = 'shoot2'; // Xbow
export const SHOOTF = 'shootF'; // What is this for? Gun? Crit? FA?
export const STAB1 = 'stabO1'; // One Handed Stab
export const STAB2 = 'stabO2'; // One Handed Punch
export const STABF = 'stabOF'; // One Handed Final Attack (Chidori)
export const SPEAR1 = 'stabT1'; // Two Handed Spear Stab
export const SPEAR2 = 'stabT2'; // Two Handed Spear Stab
export const SPEARF = 'stabTF'; // Two Handed Spear Final Attack
export const SWING1 = 'swingO1'; // One Handed Swing
export const SWING2 = 'swingO2'; // One Handed Swing
export const SWING3 = 'swingO3'; // One Handed Swing
export const SWINGF = 'swingOF'; // One Handed Swing Final Attack
export const POLEARM1 = 'stabP1'; // Two Handed Polearm Swing
export const POLEARM2 = 'stabP2'; // Two Handed Polearm Swing
export const POLEARMF = 'stabPF'; // Two Handed Polearm Final Attack
export const GREATSWORD1 = 'swingT1'; // Two Handed Sword Swing
export const GREATSWORD2 = 'swingT2'; // Two Handed Sword Swing
export const GREATSWORD3 = 'swingT3'; // Two Handed Sword Swing
export const GREATSWORDF = 'swingTF'; // Two Handed Sword Swing Final Attack